# permissions for end users to edit pvcexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pvcexport-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-demo
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: pvcexport-editor-role
rules:
- apiGroups:
  - cloud.beifeng.com.cloud.beifeng.com
  resources:
  - pvcexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.beifeng.com.cloud.beifeng.com
  resources:
  - pvcexports/status
  verbs:
  - get
